### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by sandykurniawan19** [willkg/dennis#87]
Dennis: '0.7'
Python: '3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)]'
Command line: ['C:\\Python34\\Scripts\\dennis-cmd', 'lint', '--errorsonly', 'locale/']
Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\dennis-cmd.exe\__main__.py", line 9, in <module>
    sys.exit(click_run())
  File "c:\python34\lib\site-packages\dennis\cmdline.py", line 156, in click_run
    cli(obj={})
  File "c:\python34\lib\site-packages\click\core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "c:\python34\lib\site-packages\click\core.py", line 644, in main
    rv = self.invoke(ctx)
  File "c:\python34\lib\site-packages\click\core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python34\lib\site-packages\click\core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python34\lib\site-packages\click\core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "c:\python34\lib\site-packages\dennis\cmdline.py", line 312, in lint
    out(withlines(msg.poentry.linenum, msg.poentry.original))
  File "c:\python34\lib\site-packages\dennis\cmdline.py", line 50, in out
    click.echo(part, nl=False)
  File "c:\python34\lib\site-packages\click\utils.py", line 293, in echo
    file.write(message)
  File "c:\python34\lib\site-packages\click\_compat.py", line 504, in _safe_write
    return _write(s)
  File "c:\python34\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "c:\python34\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "c:\python34\lib\site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\python34\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\python34\lib\encodings\cp850.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 97-134: character maps to <undefined>

---

**Comment by willkg** [comment]
Thank you for reporting this! I really appreciate it!

I don't use Windows, so I haven't tested Dennis on it and I don't think anyone else has, either. I suspect this is probably one of several problems that running Dennis on Windows will have.

I'm going to change this bug to "support Windows" because I think that's the bigger issue here.

Are you using this on an Open Source project or for a corporate project?

I ask because I'm not sure adding Windows support is something I will do, but if someone else is willing to do the work, I'll happily review it and help where I can. If it's important and there's some urgency, then paying someone to do the work is probably the most expedient way to get this fixed.

**Comment by sandykurniawan19** [comment]
I tested the file translate de. po in a project people @willkg  , I'm sorry, you've made a fuss
